#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
        stat_busy "Starting Music Player Stats Daemon"
        /usr/local/bin/mpdsd start &> /dev/null
        if [ $? -gt 0 ]; then
                stat_fail
        else
                add_daemon mpdsd
                stat_done
        fi
        ;;
  stop)
        stat_busy "Stopping Music Player Stats Daemon"
        /usr/local/bin/mpdsd stop &> /dev/null
        if [ $? -gt 0 ]; then
                stat_fail
        else
                rm_daemon mpdsd
                stat_done
        fi
        ;;
  restart)
        $0 stop
        sleep 1
        $0 start
        ;;
  *)
        echo "usage: $0 {start|stop|restart}"
esac
exit 0
